In [1]:
!python -m pip install numpy

In [2]:
import numpy as np

In [3]:
num_list = [1, 2, 3, 4]
int_arr2 = np.array(num_list)
print(type(num_list), type(int_arr2))
print(num_list)
print(int_arr2)

<class 'list'> <class 'numpy.ndarray'>
[1, 2, 3, 4]
[1 2 3 4]


In [5]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.array([1, '2', 3])

array(['1', '2', '3'], dtype='<U21')

In [ ]:
np.array([1, 2., 3])

array([1., 2., 3.])

In [12]:
np.array([1, True, 3, 4.])

array([1., 1., 3., 4.])

In [10]:
arr1 = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]
)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr2 = np.array(
    [
        [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]],

        [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],
    ]
)
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [14]:
print(arr1.ndim, arr1.shape)

2 (3, 4)


In [15]:
print(arr2.ndim, arr2.shape)

3 (2, 3, 4)


In [ ]:
arr3 = np.arange(1, 11)

print(arr3)
print(arr3.ndim, arr3.shape)
# (10,) != (10)
# (10,) != (10,0)
# (10,) != (10,1)

[ 1  2  3  4  5  6  7  8  9 10]
1 (10,)


In [ ]:
arr4 = arr3.reshape(2, 5)
print(arr4.ndim, arr4.shape)
print(arr4)

2 (2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
arr5 = arr3.reshape(-1, 5)
print(arr5.ndim, arr5.shape)
print(arr5)

2 (2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [24]:
print(a + 1)
print(a - 1)
print(a * 3)
print(a / 2)

[2 3 4]
[0 1 2]
[3 6 9]
[0.5 1.  1.5]


In [25]:
arr6 = np.linspace(1, 10, 10)
print(arr6.dtype)
print(arr6)

float64
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [26]:
arr7 = np.linspace(0, np.pi, 10)
print(arr7.dtype)
print(arr7)

float64
[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


In [29]:
arr8 = np.zeros(10)
print(arr8)

arr9 = np.zeros(10, dtype=int)
print(arr9)

arr10 = np.zeros((2, 5))
print(arr10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
