In [1]:
!python -m pip install numpy

In [2]:
import numpy as np

In [3]:
num_list = [1, 2, 3, 4]
int_arr2 = np.array(num_list)
print(type(num_list), type(int_arr2))
print(num_list)
print(int_arr2)

<class 'list'> <class 'numpy.ndarray'>
[1, 2, 3, 4]
[1 2 3 4]


In [5]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.array([1, '2', 3])

array(['1', '2', '3'], dtype='<U21')

In [ ]:
np.array([1, 2., 3])

array([1., 2., 3.])

In [12]:
np.array([1, True, 3, 4.])

array([1., 1., 3., 4.])

In [10]:
arr1 = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]
)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr2 = np.array(
    [
        [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]],

        [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],
    ]
)
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [14]:
print(arr1.ndim, arr1.shape)

2 (3, 4)


In [15]:
print(arr2.ndim, arr2.shape)

3 (2, 3, 4)


In [ ]:
arr3 = np.arange(1, 11)

print(arr3)
print(arr3.ndim, arr3.shape)
# (10,) != (10)
# (10,) != (10,0)
# (10,) != (10,1)

[ 1  2  3  4  5  6  7  8  9 10]
1 (10,)


In [ ]:
arr4 = arr3.reshape(2, 5)
print(arr4.ndim, arr4.shape)
print(arr4)

2 (2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
arr5 = arr3.reshape(-1, 5)
print(arr5.ndim, arr5.shape)
print(arr5)

2 (2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [24]:
print(a + 1)
print(a - 1)
print(a * 3)
print(a / 2)

[2 3 4]
[0 1 2]
[3 6 9]
[0.5 1.  1.5]


In [74]:
print(a % 2)
print(a % 2 == 0)

[1 0 1]
[False  True False]


In [25]:
arr6 = np.linspace(1, 10, 10)
print(arr6.dtype)
print(arr6)

float64
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [26]:
arr7 = np.linspace(0, np.pi, 10)
print(arr7.dtype)
print(arr7)

float64
[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


In [29]:
arr8 = np.zeros(10)
print(arr8)

arr9 = np.zeros(10, dtype=int)
print(arr9)

arr10 = np.zeros((2, 5))
print(arr10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
data1 = list(range(0, 10))
print(data1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [31]:
data2 = []
for x in data1:
    data2.append(x * 2)

data2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [32]:
data3 = [x * 2 for x in data1]
data3

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [34]:
list(map(lambda x: x*2, data1))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [36]:
x = np.array(data1)
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
c = np.array([1, 2, 3])
d = np.array([10, 20, 30])

print(2 * c + d)
print(c == 2)
print(d > 10)
print((c == 2) & (d > 10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [44]:
g = np.array([[0, 1, 2], [3, 4, 5]])
g

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
print(g.ndim, g.shape)

2 (2, 3)


In [47]:
h= np.array(
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]
        ],
        [
            [11, 12, 13, 14],
            [15, 16, 17, 18],
            [19, 20, 21, 22]
        ]
    ]
)
print(h.ndim, h.shape, h.size)
h

3 (2, 3, 4) 24


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [50]:
i = np.array([0, 1, 2, 3, 4])
print(i[2])
print(i[-1])
print(i[1 : -2])

2
4
[1 2]


In [51]:
j = np.array([[0, 1, 2], [3, 4, 5]])
j

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
print(j[0][0])
print(j[0, 0])

0
0


In [56]:
print(j[0][1])
print(j[0, 1])

1
1


In [57]:
print(j[1][2])
print(j[1, 2])

5
5


In [58]:
print(j[0])

[0 1 2]


In [65]:
print(j[:, 1])
print(j[0:2, 1])

[1 4]
[1 4]


In [ ]:
print(j[1, 1:])

[4 5]


In [69]:
print(j[:2, :2])

[[0 1]
 [3 4]]


In [70]:
k = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(k[:2, :2])

[[0 1]
 [4 5]]


In [71]:
l = np.array(range(0, 10))
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])
l[idx]

array([0, 2, 4, 6, 8])

In [72]:
temp1 = l % 2 == 0
temp1

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [75]:
l[temp1]

array([0, 2, 4, 6, 8])

In [76]:
l[l % 2 == 0]

array([0, 2, 4, 6, 8])

In [77]:
m = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
m[ (m % 4 == 1) | (m % 4 == 0) ]

array([ 1,  4,  5,  8,  9, 12])

In [79]:
m[[2, 0, 1]]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [81]:
x = np.arange(1, 21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
x[ x % 3 == 0 ]

array([ 3,  6,  9, 12, 15, 18])

In [83]:
x[ x % 4 == 1 ]

array([ 1,  5,  9, 13, 17])

In [84]:
x[ (x % 3 == 0) & (x % 4 == 1) ]

array([9])